Name: product.rpc
ListenOn: 127.0.0.1:9001

Etcd:
  Hosts:
    - 123.56.113.66:12379
  Key: product.rpc

Mysql:
  DataSource: root:123123@tcp(127.0.0.1:3306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: 127.0.0.1:6379
    Type: node # node可以不写，可以设为cluster
    Pass: 123123 # 如果有密码
