// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"product/service/user/rpc/internal/logic"
	"product/service/user/rpc/internal/svc"
	"product/service/user/rpc/pb/userclient"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	userclient.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *userclient.LoginRequest) (*userclient.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(ctx, in)
}

func (s *UserServer) Register(ctx context.Context, in *userclient.RegisterRequest) (*userclient.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(ctx, in)
}

func (s *UserServer) UserInfo(ctx context.Context, in *userclient.UserInfoRequest) (*userclient.UserInfoResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(ctx, in)
}

func (s *UserServer) GetUser(ctx context.Context, in *userclient.GetUserRequest) (*userclient.GetUserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(ctx, in)
}
